---

- name: ensure logrotate is installed
  yum:
    name: logrotate
    state: installed

- name: set logrotate interval to daily
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    line: "daily"
    backrefs: yes

- name: set logrotate retention period to 7 days
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^rotate 4'
    line: "rotate 7"
    backrefs: yes

- name: set logrotate retention period to 7 days
  file:
    path: /etc/logrotate.d
    state: directory
    mode: 0755
