---

- name: ensure logrotate is installed
  yum:
    name: logrotate
    state: installed

- name: set logrotate interval to daily
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    line: "daily"
    backrefs: yes

- name: set logrotate retention period to 7 days
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^rotate 4'
    line: "rotate 7"
    backrefs: yes

- name: enable logrotate compression
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^#compress'
    line: "compress"
    backrefs: yes

- name: ensure logrotate.d directory exists
  file:
    path: /etc/logrotate.d
    state: directory
    mode: 0755

- name: ensure group "logread" exists
  group:
    name: logread
    system: yes
    state: present

- name: syslog rotation
  template:
    src: syslog.j2
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644

- name: stat /var/log/messages
  stat:
    path: /var/log/messages
  register: logrotate_var_log_messages

- name: stat /var/log/cron
  stat:
    path: /var/log/cron
  register: logrotate_var_log_cron

- name: grant logread group access
  acl:
    path: "{{ item.path }}"
    entity: logread
    etype: group
    permissions: r
    state: present
  when: item.enabled
  with_items:
  - { path: '/var/log/messages', enabled: "{{ logrotate_var_log_messages.stat.exists }}" }
  - { path: '/var/log/cron', enabled: "{{ logrotate_var_log_cron.stat.exists }}" }
  tags:
  - molecule-idempotence-notest
